do_train: True
do_eval: True
seed: 42
model_name_or_path: "microsoft/unixcoder-base"
train_filename: "dataset/python/train.jsonl"
dev_filename: "dataset/python/valid.jsonl"
test_filename: null
output_dir: "saved_models/python"
max_source_length: 256
max_target_length: 128
beam_size: 10
n_gpu: 1
weight_decay: 0.0
adam_epsilon: 1e-8
max_grad_norm: 1.0
train_batch_size: 48
eval_batch_size: 48
learning_rate: 5e-5
gradient_accumulation_steps: 2
num_train_epochs: 3